from enum import IntEnum

USER_MARK = "U"
COMPUTER_MARK = "C"
NOBODY_MARK = " "

SQUARES_NUMBER = 9

SQUARE_NOT_FOUND = -1


class SQUARES(IntEnum):
    TOP_LEFT = 0
    TOP_CENTER = 1
    TOP_RIGHT = 2
    MIDDLE_LEFT = 3
    MIDDLE_CENTER = 4
    MIDDLE_RIGHT = 5
    BOTTOM_LEFT = 6
    BOTTOM_CENTER = 7
    BOTTOM_RIGHT = 8


ROWS_OF_SQUARES = (
    (SQUARES.TOP_LEFT, SQUARES.TOP_CENTER, SQUARES.TOP_RIGHT),
    (SQUARES.MIDDLE_LEFT, SQUARES.MIDDLE_CENTER, SQUARES.MIDDLE_RIGHT),
    (SQUARES.BOTTOM_LEFT, SQUARES.BOTTOM_CENTER, SQUARES.BOTTOM_RIGHT),
    (SQUARES.TOP_LEFT, SQUARES.MIDDLE_LEFT, SQUARES.BOTTOM_LEFT),
    (SQUARES.TOP_CENTER, SQUARES.MIDDLE_CENTER, SQUARES.BOTTOM_CENTER),
    (SQUARES.TOP_RIGHT, SQUARES.MIDDLE_RIGHT, SQUARES.BOTTOM_RIGHT),
    (SQUARES.TOP_LEFT, SQUARES.MIDDLE_CENTER, SQUARES.BOTTOM_RIGHT),
    (SQUARES.TOP_RIGHT, SQUARES.MIDDLE_CENTER, SQUARES.BOTTOM_LEFT),
)

ROWS_OF_SQUARES_DOUBLE = (
    (
        SQUARES.TOP_LEFT,
        SQUARES.TOP_CENTER,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_LEFT,
        SQUARES.BOTTOM_LEFT,
    ),
    (
        SQUARES.TOP_LEFT,
        SQUARES.TOP_CENTER,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_RIGHT,
    ),
    (
        SQUARES.TOP_LEFT,
        SQUARES.MIDDLE_LEFT,
        SQUARES.BOTTOM_LEFT,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_RIGHT,
    ),
    (
        SQUARES.TOP_RIGHT,
        SQUARES.TOP_LEFT,
        SQUARES.TOP_CENTER,
        SQUARES.MIDDLE_RIGHT,
        SQUARES.BOTTOM_RIGHT,
    ),
    (
        SQUARES.TOP_RIGHT,
        SQUARES.TOP_LEFT,
        SQUARES.TOP_CENTER,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_LEFT,
    ),
    (
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_RIGHT,
        SQUARES.BOTTOM_RIGHT,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_LEFT,
    ),
    (
        SQUARES.BOTTOM_LEFT,
        SQUARES.TOP_LEFT,
        SQUARES.MIDDLE_LEFT,
        SQUARES.BOTTOM_CENTER,
        SQUARES.BOTTOM_RIGHT,
    ),
    (
        SQUARES.BOTTOM_LEFT,
        SQUARES.TOP_LEFT,
        SQUARES.MIDDLE_LEFT,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_CENTER,
    ),
    (
        SQUARES.BOTTOM_LEFT,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_CENTER,
        SQUARES.BOTTOM_RIGHT,
    ),
    (
        SQUARES.BOTTOM_RIGHT,
        SQUARES.BOTTOM_LEFT,
        SQUARES.BOTTOM_CENTER,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_RIGHT,
    ),
    (
        SQUARES.BOTTOM_RIGHT,
        SQUARES.BOTTOM_LEFT,
        SQUARES.BOTTOM_CENTER,
        SQUARES.TOP_LEFT,
        SQUARES.MIDDLE_CENTER,
    ),
    (
        SQUARES.BOTTOM_RIGHT,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_RIGHT,
        SQUARES.TOP_LEFT,
        SQUARES.MIDDLE_CENTER,
    ),
    (
        SQUARES.TOP_CENTER,
        SQUARES.TOP_LEFT,
        SQUARES.TOP_RIGHT,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_CENTER,
    ),
    (
        SQUARES.MIDDLE_LEFT,
        SQUARES.TOP_LEFT,
        SQUARES.BOTTOM_LEFT,
        SQUARES.MIDDLE_CENTER,
        SQUARES.MIDDLE_RIGHT,
    ),
    (
        SQUARES.MIDDLE_RIGHT,
        SQUARES.TOP_RIGHT,
        SQUARES.BOTTOM_RIGHT,
        SQUARES.MIDDLE_LEFT,
        SQUARES.MIDDLE_CENTER,
    ),
    (
        SQUARES.BOTTOM_CENTER,
        SQUARES.TOP_CENTER,
        SQUARES.MIDDLE_CENTER,
        SQUARES.BOTTOM_LEFT,
        SQUARES.BOTTOM_RIGHT,
    ),
)
